# Generated by Django 3.2.9 on 2024-10-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_auto_20241021_0206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialNetworkModel',
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook manzili'),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram manzili'),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='youtube',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Youtube manzili'),
        ),
        migrations.AlterField(
            model_name='sitemodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Elektron pochta manzili'),
        ),
        migrations.AlterField(
            model_name='sitemodel',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Servis manzili'),
        ),
        migrations.AlterField(
            model_name='sitemodel',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='sitemodel',
            name='site_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sayt nomi'),
        ),
    ]
