# Generated by Django 5.1.4 on 2024-12-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0003_auto_20241021_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemodel',
            name='telegram_bot',
            field=models.TextField(blank=True, null=True, verbose_name='Telegram bot'),
        ),
    ]
