# Generated by Django 5.1.4 on 2024-12-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0004_sitemodel_telegram_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemodel',
            name='telegram_bot',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telegram bot manzili'),
        ),
    ]
