# Generated by Django 3.2.9 on 2024-10-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='about_us')),
                ('image2', models.ImageField(upload_to='about_us')),
            ],
            options={
                'verbose_name': 'Kompaniya Haqida',
                'verbose_name_plural': 'Kompaniyaning Haqida',
            },
        ),
    ]
