# Generated by Django 3.2.9 on 2024-10-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusmodel',
            name='description',
            field=models.TextField(verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='aboutusmodel',
            name='image1',
            field=models.ImageField(upload_to='about_us', verbose_name='Rasm1'),
        ),
        migrations.AlterField(
            model_name='aboutusmodel',
            name='image2',
            field=models.ImageField(upload_to='about_us', verbose_name='Rasm2'),
        ),
        migrations.AlterField(
            model_name='aboutusmodel',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
    ]
