# Generated by Django 3.2.9 on 2024-10-24 05:27

from django.db import migrations, models
import team.models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20241024_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews', validators=[team.models.validate_image_dimensions_review, team.models.validate_image_format]),
        ),
    ]
