# Generated by Django 5.1.4 on 2024-12-29 15:24

import team.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_reviewmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='description',
            field=models.TextField(verbose_name='Sharh matni'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='first_name',
            field=models.CharField(max_length=80, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews', validators=[team.models.validate_image_dimensions_review, team.models.validate_image_format], verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='last_name',
            field=models.CharField(max_length=80, verbose_name='Familiya'),
        ),
    ]
