# Generated by Django 3.2.9 on 2024-10-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuremodel',
            name='description',
            field=models.TextField(verbose_name="Xususiyat haqida ma'lumot"),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='image',
            field=models.ImageField(upload_to='features', verbose_name='Xususiyat rasmi'),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol xususiyat'),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Xususiyat nomi'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='description',
            field=models.TextField(verbose_name="Xizmat haqida ma'lumot"),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='image',
            field=models.ImageField(upload_to='services', verbose_name='Xizmat rasmi'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol xizmat'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Xizmat narxi'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Xizmat nomi'),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='description',
            field=models.TextField(verbose_name="Qilgan ishingiz haqida ma'lumot"),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='image',
            field=models.ImageField(upload_to='works', verbose_name='Qilgan ishingiz rasmi'),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol ish'),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Qilgan ishingiz nomi'),
        ),
    ]
