# Generated by Django 3.2.9 on 2024-10-22 17:19

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20241021_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicemodel',
            options={'verbose_name': 'Xizmat', 'verbose_name_plural': 'Xizmatlarimiz'},
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='image',
            field=models.ImageField(upload_to='services', validators=[services.models.validate_image], verbose_name='Xizmat rasmi'),
        ),
    ]
