# Generated by Django 3.2.9 on 2024-10-23 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('services', '0003_auto_20241022_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuremodel',
            options={'verbose_name': 'Qulaylik', 'verbose_name_plural': 'Qulayliklarimiz'},
        ),
        migrations.AddField(
            model_name='workmodel',
            name='who_did',
            field=models.ForeignKey(help_text="Agar bu ishni jamoa bilan birga qilingan bo'linsa, hech nima tanlanmasa o'zi jamoa bilan bo'lib tanlanadi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='team.teammodel', verbose_name='Bu ishni kim bajargan'),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='description',
            field=models.TextField(verbose_name="Qulaylik haqida ma'lumot"),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='image',
            field=models.ImageField(upload_to='features', verbose_name='Qulaylik rasmi'),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Qulaylik nomi'),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Agar bu ekranga chiqishni xoxlasayiz tugma tanlangan bo'lishi kerak, aks holda bu ekranga chiqmaydi. Faqatgina bazada saqlanib turadi", verbose_name='Faol ish'),
        ),
    ]
