# Generated by Django 3.2.9 on 2024-10-23 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('services', '0004_auto_20241023_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmodel',
            name='who_did',
            field=models.ForeignKey(blank=True, help_text="Agar bu ishni jamoa bilan birga qilingan bo'linsa, hech nima tanlanmasa o'zi jamoa bilan bo'lib tanlanadi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='team.teammodel', verbose_name='Bu ishni kim bajargan'),
        ),
    ]
