# Generated by Django 3.2.9 on 2024-10-20 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecarouselmodel',
            options={'verbose_name': 'Asosiy Karusel', 'verbose_name_plural': 'Asosiy Karusellar'},
        ),
    ]
