# Generated by Django 3.2.9 on 2024-10-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_basecarouselmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecarouselmodel',
            name='background_image',
            field=models.ImageField(upload_to='carousel', verbose_name='Asosiy rasm'),
        ),
        migrations.AlterField(
            model_name='basecarouselmodel',
            name='description',
            field=models.TextField(verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='basecarouselmodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlavha'),
        ),
    ]
